[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
bindeps = true

[build]
target = "hrckern.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"